MVCDay/Controllers/RegFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCDay.Models;
using System.Data.Objects;

namespace MVCDay.Controllers
{
    public class RegFormController : Controller
    {
        LTIMVCEntities1 db = new LTIMVCEntities1();
//----------------------------------insertnew employee----------------------------------
        [HttpGet]
        public ActionResult InsertNewEmployee()
        {
            //this code will retrieve data from db and bind it to DropDownList
            //frm where we r selecting data-selecting from projectinfo
            //projid-->value member
            //projname-->display memeber--end user will see project names
            ViewData["proj"] = new SelectList(db.ProjectInfoes.ToList(),"projid","projname");
            return View();
        }
        //method name and view name must be same
        [HttpPost]
        public ActionResult InsertNewEmployee(Employee emp)
        {

            emp.EmpID = Convert.ToInt32(Request.Form["txtempid"]);
            emp.EmpName = Request.Form["txtempname"];
            emp.Dept = Request.Form["depart"];
            emp.Desg = Request.Form["ddldesg"];
            emp.Salary = Convert.ToDecimal(Request.Form["txtSalary"]);
            emp.projid = Convert.ToInt32(Request.Form["ddlpid"]);

            //this data has to be inserted to DB
            //ado.net or new technology called entity framework
            //ModelState.AddModelError() display any msg from controller
            //in the view
            ModelState.AddModelError("", emp.EmpID + "," + emp.EmpName + "," + emp.Dept + "," + emp.Desg + "," + emp.Salary+","+emp.projid);
            //1. obj of sqlconnection
            //2.open connection 
            //3.

            //insert data to emp table through entity framework
            db.Employees.Add(emp);
            int res = db.SaveChanges();
            if (res > 0)
                ModelState.AddModelError("", "new employee inserted");
            return RedirectToAction("GetEmployees"); //1st way
            
        }
//---------------------------------------get employees---------------------------------------------------------------------------------------
        public ActionResult GetEmployees()
        {
            var data = db.Employees.ToList();
            return View(data);//model binding

        }
//-----------------------------get emp by dept and salary----------------------------------------------------------------------------
        //retrieve emp details from the db on condidtion
        [HttpGet]
        public ActionResult GetEmployeeByDeptSalary()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GetEmployeeByDeptSalary(string dept,decimal? salary)
        {
            dept = Request.Form["dept"];
            salary = Convert.ToDecimal(Request.Form["Salary"]);
            var query = from t in db.Employees
                        where t.Dept == dept && t.Salary >= salary
                        select t;
            var lambda = db.Employees.Where(x => x.Dept == dept && x.Salary >= salary);
            if(query.Count()==0)
            {
                ModelState.AddModelError("", "No data found for the parameters passed");
                return View();
            }
            else
            {
                //this will pass data from controller 
                //to view
                Session["data"] = query;
            }
            return View();
        }
//----------------------------------------update employee---------------------------------------------------------------------

        [HttpGet]
        public ActionResult UpdateEmployee(int id)
        {
            var data = db.Employees.Where(x => x.EmpID == id).SingleOrDefault();

            return View(data);
        }
        [HttpPost]
        public ActionResult UpdateEmployee()
        {
            int id = Convert.ToInt32(Request.Form["eid"]);
            var olddata = db.Employees.Where(x => x.EmpID == id).SingleOrDefault();
            var newname = Request.Form["name"];
            var newdept = Request.Form["dept"];
            var newdesg = Request.Form["desg"];
            var newsal=Convert.ToDecimal (Request.Form["sal"]);
            var newpid = Convert.ToInt32(Request.Form["pid"]);
            olddata.EmpName = newname;
            olddata.Dept = newdept;
            olddata.Desg = newdesg;
            olddata.Salary = newsal;
            olddata.projid = newpid;
            olddata.EmpID = id;
            
            var res = db.SaveChanges();
            if (res > 0)
                return RedirectToAction("GetEmployees");
            return RedirectToAction("InsertNewEmployee");
            
        }
//---------------------------------------delete employee--------------------------------------------------------
        [HttpGet]
        public ActionResult DeleteEmployee(int id)
        {
            var data = db.Employees.Where(x => x.EmpID == id).SingleOrDefault();

            return View(data);
        }
        [HttpPost]
        public ActionResult DeleteEmployee()
        {
            int id = Convert.ToInt32(Request.Form["eid"]);
            var delrow = db.Employees.Where(x => x.EmpID == id).SingleOrDefault();
            db.Employees.Remove(delrow);
            var res = db.SaveChanges();
            if (res > 0)
                return RedirectToAction("GetEmployees");
            return RedirectToAction("GetEmployees");
        }
//---------------------------------------insert project--------------------------------------------------------

        [HttpGet]
        public ActionResult InsertProject()
        {
            return View();
        }
        [HttpPost]
        public ActionResult InsertProject(ProjectInfo pinfo)
        {
            if(ModelState.IsValid)
            {
                //if there is no validation error,then 
                //Isvalid will return true
                //if errors IsValid return false
                db.ProjectInfoes.Add(pinfo);
                var res = db.SaveChanges();
                if (res > 0)
                {
                    Response.Write("<script type='text/JavaScript'>" + "alert('New Project Crreated')" + "</script");
                    ModelState.AddModelError("", "New Project Added");
                }//res
            }//isvalid
            return View();
        }
//_-----------------------------------------Get Emp Project-----------------------------------------
        [HttpGet]
        public ActionResult GetEmpProject()
        {
            var data = (from e in db.Employees
                       join p in db.ProjectInfoes
                       on e.projid equals p.projid
                       select new CustomEmpProject { EmpId = e.EmpID, Name = e.EmpName, Dept = e.Dept, ProjName = p.projname, Domain = p.domain }).ToList();
            return View(data);
        }
//---------------------------storded procedure--------------------------------------------------
        [HttpGet]
        public ActionResult SelectAndUpdateProjectSP()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SelectandUpdateProjectSP(string command)
        {
            if (command == "Select")
            {
                int? id = int.Parse(Request.Form["pid"]);
                var result = db.sp_SelectProjectById(id).FirstOrDefault();
                if (result == null)
                    ModelState.AddModelError("", "Invalid project id");
                else
                
                    ModelState.AddModelError("", result.projid + "," + result.projname + "," + result.domain);
                
                ViewBag.data = result;
            }
            if (command == "Update")
            {
                string newpname = Request.Form["pname"];
                string newdomain = Request.Form["domain"];
                int? pid = int.Parse(Request.Form["projid"]);
                var res = db.sp_UpdateProject(pid, newpname, newdomain);
                if (res > 0)
                    ModelState.AddModelError("", "one row affected");
            }

            return View();

        }
    }

}

MVCDay/Views/RegForm/DeleteEmployee.cshtml
@model MVCDay.Models.Employee
@{
    ViewBag.Title = "DeleteEmployee";
}

<h2>DeleteEmployee</h2>
@using (Html.BeginForm())
{
    <div>
        EmpID:<input type="text" name="eid" value=@Model.EmpID readonly />
    </div>
    <div>
        EmpName:<input type="text" name="name" value=@Model.EmpName readonly />
    </div>
    <div>
        Dept:<input type="text" name="dept" value=@Model.Dept readonly />
    </div>
    <div>
        Desg:<input type="text" name="desg" value=@Model.Desg readonly />
    </div>
    <div>
        Salary:<input type="text" name="sal" value=@Model.Salary readonly />
    </div>
    <div>
        ProjectID:<input type="text" name="pid" value=@Model.projid readonly/>
    </div>
    <div>
        <input type="submit" value="Delete" />
    </div>
}

MVCDay/Views/RegForm/GetEmpProject.cshtml
@model IEnumerable<MVCDay.Models.CustomEmpProject>
@{
    ViewBag.Title = "GetEmpProject";
}

<h2>Get Emp Project</h2>
<table border="1">
    <tr>
        <th>EmpID</th>
        <th>Name</th>
        <th>Dept</th>
        <th>ProjName</th>
        <th>Domain</th>
    </tr>
    @foreach(var m in Model)
    {
<tr>
    <td>@m.EmpId</td>
    <td>@m.Name</td>
    <td>@m.Dept</td>
    <td>@m.ProjName</td>
    <td>@m.Domain</td>
</tr>
    }
</table>
<div>
    @Html.ActionLink("New Employee","InsertNewEmployee")
</div>

MVCDay/Views/RegForm/GetEmployeeByDeptSalary.cshtml
@using System.Collections.Generic;
@{
    ViewBag.Title = "GetEmployeeByDeptSalary";
}

<h2>GetEmployeeByDeptSalary</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div>
        Enter DeptName:<input type="text" name="dept" />
    </div>
    <div>
        Enter Salary:@Html.TextBox("Salary")
    </div>
    <div>
        <input type="submit" value="Select" />
    </div>

    if (Session["data"] != null)
    {
        IQueryable<MVCDay.Models.Employee> emp =
            (IQueryable<MVCDay.Models.Employee>)Session["data"]; //typecasting
        <table border="1">
            @foreach (var e in emp)
            {
                <tr>
                    <td>@e.EmpID</td>
                    <td>@e.EmpName</td>
                    <td>@e.Dept</td>
                    <td>@e.Desg</td>
                    <td>@e.Salary</td>
                    <td>@e.projid</td>
                </tr>
            }
        </table>
    }
}

    <div>
        @Html.ActionLink("Insert New","InsertNewEmployee")
    </div>

MVCDay/Views/RegForm/GetEmployees.cshtml
@model List<MVCDay.Models.Employee>
@{
    ViewBag.Title = "GetEmployees";
}

<h2>GetEmployees</h2>
<table border="1">
    <tr>
        <th>EmpID</th>
        <th>EmpName</th>
        <th>Dept</th>
        <th>Desg</th>
        <th>Salary</th>
        <th>Project ID</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    @foreach (var m in Model)
    {
<tr>
    <td>@m.EmpID</td>
    <td>@m.EmpName</td>
    <td>@m.Dept</td>
    <td>@m.Desg</td>
    <td>@m.Salary</td>
    <td>@m.projid</td>
    <td>@Html.ActionLink("Edit:" + m.EmpID, "UpdateEmployee", "RegForm", new { id = m.EmpID },null)</td>
    <td>@Html.ActionLink("Delete:" + m.EmpID, "DeleteEmployee", "RegForm", new { id = m.EmpID },null)</td>
</tr>
    }
</table>
<div>
    @Html.ActionLink("Insert New", "InsertNewEmployee")
</div>

MVCDay/Views/RegForm/InsertNewEmployee.cshtml
@{
    ViewBag.Title = "InsertNewEmployee";
}

<h2>InsertNewEmployee</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <table border="1">
        <tr>
            <td>Enter EmpID</td>
            <td>@Html.TextBox("txtempid")</td>
        </tr>
        <tr>
            <td>Enter Name</td>
            <td>@Html.TextBox("txtempname")</td>
        </tr>
        <tr>
            <td>Enter Department</td>
            <td>
                @Html.DropDownList("depart", new List<SelectListItem> {
           new SelectListItem{Text="IT",Value="IT"},
           new SelectListItem{Text="ACCOUNTS",Value="ACCT"},
           new SelectListItem{Text="HR",Value="HR"},
           new SelectListItem{Text="Manager",Value="Manager"}
       })
        </td>
    </tr>
    <tr>
        <td>Select designation</td>
        <td>
            <select name="ddldesg">
                <option value="Traineee">Trainee</option>
                <option value="Sr.Exec">Senior Executive</option>
                <option value="Manager">Manager</option>
                <option value="CEO">CEO</option>
            </select>
        </td>
    </tr>
    <tr>
        <td>Enter Salary</td>
        <td>
            <input type="number" name="txtSalary" />
        </td>
    </tr>
        <tr>
            <td>Select Projid</td>
            <td>@Html.DropDownList("ddlpid",ViewData["proj"]as SelectList)</td>
        </tr>
    <tr>
        <td><input type="submit" value="New Registration" /></td>
        <td><input type="reset" value="Cancel" /></td>
    </tr>
</table>
}
<div>
    @Html.ActionLink("Select Employee", "GetEmployees")
    @*this is html helper for <a href="">*@
</div>
<div>
    @Html.ActionLink("Select Employee By Dept and Salary", "GetEmployeeByDeptSalary")
</div>
<div>
    @Html.ActionLink("Insert Project","InsertProject")
</div>
<div>
    @Html.ActionLink("Get EmpProj Details", "GetEmpProject")
</div>
<div>
    @Html.ActionLink("Call SP" , "SelectAndUpdateProjectSP")
</div>

MVCDay/Views/RegForm/InsertProject.cshtml
@model MVCDay.Models.ProjectInfo
@{
    ViewBag.Title = "InsertProject";
}

<h2>InsertProject</h2>

<form method="post">
    @Html.ValidationSummary(true)
    <div>
        Enter Project Name
        @Html.TextBoxFor(x => x.projname)
        @Html.ValidationMessageFor(x => x.projname)
    </div>
    <div>
        Enter Domain
        @Html.TextBoxFor(x => x.domain)
        @Html.ValidationMessageFor(x => x.domain)
    </div>
    <div>
       <input type="submit" value="Insert NewProject"/>
        
    </div>
</form>
<div>
    @Html.ActionLink("Insert Employee", "InsertNewEmployee")
</div>

MVCDay/Views/RegForm/SelectAndUpdateProjectSP.cshtml
@{
    ViewBag.Title = "SelectAndUpdateProjectSP";
}

<h2>SelectAndUpdateProjectSP</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div>
        ProjID:<input type="text" name="pid" />

    </div>
    <div>
        <input type="submit" value="Select" name="command"/>
    </div>
    <hr />
    if (ViewBag.data != null)
    {
        <div>
            Project ID:<input type="text" name="projid" value=@ViewBag.data.projid readonly/>
        </div>
        <div>
            ProjectName:<input type="text" name="pname" value=@ViewBag.data.projname />
        </div>
        <div>
            Domain:<input type="text" name="domain" value=@ViewBag.data.domain />
        </div>
        <div>
            <input type="submit" value="Update" name="command"/>
        </div>
    }


}
<div>
    @Html.ActionLink("Insert New", "InsertNewEmployee")
</div>

MVCDay/Views/RegForm/UpdateEmployee.cshtml
@model MVCDay.Models.Employee
@{
    ViewBag.Title = "UpdateEmployee";
}

<h2>UpdateEmployee</h2>
@using (Html.BeginForm())
{
    <div>
        EmpID:<input type="text" name="eid" value=@Model.EmpID readonly />
    </div>
    <div>
        EmpName:<input type="text" name="name" value=@Model.EmpName />
    </div>
    <div>
        Dept:<input type="text" name="dept" value=@Model.Dept />
    </div>
    <div>
        Desg:<input type="text" name="desg" value=@Model.Desg />
    </div>
    <div>
        Salary:<input type="text" name="sal" value=@Model.Salary />
    </div>
    <div>
        ProjectID:<input type="text" name="pid" value=@Model.projid />
    </div>

    <div>
        <input type="submit" value="Update" />
    </div>
}